security:
    providers:
        api_key_user_provider:
            id: App\Security\ApiKeyUserprovider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: App\Security\ApiKeyAuthenticator
            #provider: api_key_user_provider

    access_control:
        - { path: ^/, roles: ROLE_API }
